import type { ActionLedger, LedgerAction } from '@/shared/schema/action-ledger';
import type { BugReportPayload } from '@/shared/types/bug-report';

function formatAction(action: LedgerAction): string {
  const target =
    action.target.label ??
    action.target.testId ??
    action.target.role ??
    action.target.css ??
    'element';

  switch (action.type) {
    case 'NAVIGATE':
      return `${action.step}. Navigate → ${action.url ?? target}`;
    case 'FILL':
      return `${action.step}. Fill "${target}" with \`${action.value ?? ''}\`${action.presetMode ? ` (${action.presetMode})` : ''}`;
    case 'CLICK':
      return `${action.step}. Click "${target}"`;
    case 'SELECT':
      return `${action.step}. Select "${target}" → \`${action.value ?? ''}\``;
    default:
      return `${action.step}. ${action.type} "${target}"`;
  }
}

export function buildBugReportPayload(input: {
  title: string;
  ledger: ActionLedger;
  stepLimit: number;
  screenshotDataUrl: string | null;
  extraNotes?: string;
}): BugReportPayload {
  const actions = input.ledger.actions.slice(-input.stepLimit);
  const stepsMarkdown = actions.map(formatAction).join('\n');
  const originDomain = input.ledger.originDomain ?? 'unknown';

  const bodyMarkdown = [
    '## Summary',
    input.extraNotes?.trim() || '_Generated by FormFlow AI — QA bug report._',
    '',
    '## Steps to reproduce',
    stepsMarkdown || '_No recorded steps — run a recording first._',
    '',
    '## Environment',
    `- **Domain:** ${originDomain}`,
    `- **Session:** ${input.ledger.sessionId}`,
    `- **Recorded at:** ${new Date(input.ledger.timestamp).toISOString()}`,
    `- **Steps included:** ${actions.length} (last ${input.stepLimit} max)`,
    input.screenshotDataUrl ? '- **Screenshot:** attached below' : '',
    '',
    '## Action ledger (neutral JSON)',
    '```json',
    JSON.stringify({ ...input.ledger, actions }, null, 2),
    '```',
  ]
    .filter(Boolean)
    .join('\n');

  return {
    title: input.title.trim() || `Bug on ${originDomain}`,
    bodyMarkdown,
    ledgerJson: JSON.stringify({ ...input.ledger, actions }, null, 2),
    screenshotDataUrl: input.screenshotDataUrl,
    stepCount: actions.length,
    originDomain,
  };
}
